{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apbsrest.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-id
  labels:
    app: {{ template "apbsrest.name" . }}
    chart: {{ template "apbsrest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    storage: id
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /api/uid/
    # TODO: 2020/07/02, Elvis - commenting out line below for now since user doesn't need access beyond retrieving a new ID
    nginx.ingress.kubernetes.io/rewrite-target: /api/uid/$2
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          # - path: /id(/?)$
          # TODO: 2020/07/02, Elvis - commenting out line below for now since user doesn't need access beyond retrieving a new ID
          - path: /id(/|$)(.*)
            backend:
              serviceName: {{ $fullName }}-id
              servicePort: http
  {{- end }}
{{- end }}
