name: Run Microservice Unit Tests
on: 
  push:
    paths:
      - '.github/workflows/unit.yaml'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/unit.yaml'
      - 'src/**'

jobs:
  id-service:
    name: ID Service
    runs-on: ubuntu-latest
    env:
      MINIO_PORT: 9000
      MINIO_URL:  localhost:9000
      MINIO_ACCESS_KEY: github
      MINIO_SECRET_KEY: githubaction
    steps:
      - name: Git checkout APBS-REST codebase
        uses: actions/checkout@v1

      - name: Setup the Python virtual environment
        working-directory: ./src/uid
        run: |
          sudo apt update
          sudo apt install -y python3-venv
          python3 -m venv venv

      - name: Install Python dependencies
        working-directory: ./src/uid
        run: |
          source venv/bin/activate
          pip install -r requirements-dev.txt

      - name: Launch MinIO container for ID registrator/validator
        working-directory: ./src/uid
        run: |
          docker run -it -d -p $MINIO_PORT:9000 \
          -e MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY\
          -e MINIO_SECRET_KEY=$MINIO_SECRET_KEY\
          minio/minio server /data

      - name: Run unit tests
        working-directory: ./src/uid
        run: |
          source venv/bin/activate
          pytest tests/
        
  storage-service:
    name : Storage Service
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout APBS-REST codebase
        uses: actions/checkout@v1
        
      - name: Setup the Python virtual environment
        working-directory: ./src/storage
        run: |
          sudo apt update
          sudo apt install -y python3-venv
          python3 -m venv venv

      - name: Install Python dependencies
        working-directory: ./src/storage
        run: |
          source venv/bin/activate
          pip install -r requirements.txt pytest
      
      - name: Run unit tests
        working-directory: ./src/storage
        run: |
          source venv/bin/activate
          pytest tests/
  
  task-service:
    name : Task Service
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout APBS-REST codebase
        uses: actions/checkout@v1
        
      - name: Setup the Python virtual environment
        working-directory: ./src/task
        run: |
          sudo apt update
          sudo apt install -y python3-venv
          python3 -m venv venv

      - name: Install Python dependencies
        working-directory: ./src/task
        run: |
          source venv/bin/activate
          pip install -r requirements-dev.txt
      
      - name: Run unit tests
        working-directory: ./src/task
        run: |
          source venv/bin/activate
          pytest -s tests/